        PARAMETER (NYEAR=1)
        PARAMETER (NLR=0)
        PARAMETER (NLA=0)
        PARAMETER (NS2=2)
        PARAMETER (MSORT=2)
        PARAMETER (NDIV=3)
        PARAMETER (MODU=6)
        PARAMETER (C0=1.33)
        PARAMETER (C1=1.7)
        PARAMETER (NBR=24)
        PARAMETER (NB=72)
        PARAMETER (NZA=5)
        PARAMETER (NRR=6)
        PARAMETER (NRE=2)
        PARAMETER (N9=10)             
*******************************************************************时间插值变量













	




                   